"""played_vids

Revision ID: 169fab57fdcf
Revises: 43d039adf7fb
Create Date: 2015-05-27 02:09:14.805835

"""

# revision identifiers, used by Alembic.
revision = '169fab57fdcf'
down_revision = '43d039adf7fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('played',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('played')
    ### end Alembic commands ###
