# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end

  # Setup ports on your local box to talk to some of the services on the Vagrant box
  # 'guest' is the Vagrant box, 'host' is your box
  config.vm.network "forwarded_port", guest: 1935, host: 1935
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.ssh.forward_agent = true

  config.vm.synced_folder "salt", "/srv/salt/"
  config.vm.synced_folder "../site", "/var/www/shitstream/project/"

  config.vm.provision :salt do |salt|
    salt.colorize = true
    salt.log_level = "info"
    salt.install_type = "git"
    salt.install_args = "v2015.5.0"
    salt.minion_config = "salt/minion"
    salt.run_highstate = true
  end
end
